# Generated by Django 5.1.6 on 2025-03-27 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('given_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('family_name', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('preferred_name', models.CharField(blank=True, max_length=200, verbose_name='Tanlangan ism')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('country', models.CharField(max_length=100, verbose_name='Davlat')),
                ('homepage', models.URLField(blank=True, verbose_name='Shaxsiy sahifa')),
                ('orcid', models.CharField(blank=True, max_length=50, verbose_name='ORCID ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biografiya')),
                ('affiliation', models.CharField(blank=True, max_length=200, verbose_name='Tashkilot')),
                ('role', models.CharField(choices=[('author', 'Muallif'), ('translator', 'Tarjimon')], default='author', max_length=20, verbose_name='Rol')),
                ('include_in_lists', models.BooleanField(default=True, verbose_name="Nashrlar ro'yxatiga kiritish")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
            },
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Konferensiya nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('submission_deadline', models.DateField(verbose_name='Maqolalar topshirish oxirgi muddati')),
                ('location', models.CharField(max_length=255, verbose_name="O'tkaziladigan joy")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('image', models.ImageField(blank=True, null=True, upload_to='conference_images/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
            ],
            options={
                'verbose_name': 'Konferensiya',
                'verbose_name_plural': 'Konferensiyalar',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('abstract', models.TextField(verbose_name='Annotatsiya')),
                ('keywords', models.CharField(max_length=255, verbose_name="Kalit so'zlar")),
                ('references', models.TextField(blank=True, verbose_name='Havolalar')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('cover_letter', models.TextField(blank=True, verbose_name="Qo'shimcha xat")),
                ('special_instructions', models.TextField(blank=True, verbose_name="Maxsus ko'rsatmalar")),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('submitted', 'Yuborilgan'), ('under_review', "Ko'rib chiqilmoqda"), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('published', 'Chop etilgan')], default='draft', max_length=20, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan sana')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_articles', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Asosiy muallif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maqola muallifi',
                'verbose_name_plural': 'Maqola mualliflari',
                'ordering': ['order'],
                'unique_together': {('article', 'author')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(related_name='articles', through='app.ArticleAuthor', to=settings.AUTH_USER_MODEL, verbose_name='Mualliflar'),
        ),
        migrations.CreateModel(
            name='ArticleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='article_files/%Y/%m/', verbose_name='Fayl')),
                ('file_name', models.CharField(max_length=255, verbose_name='Fayl nomi')),
                ('file_type', models.CharField(choices=[('article_text', 'Maqola matni'), ('dataset', "Ma'lumotlar to'plami"), ('supplementary', 'Qo‘shimcha material'), ('image', 'Rasm'), ('other', 'Boshqa')], default='other', max_length=20, verbose_name='Fayl turi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan sana')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.article', verbose_name='Maqola')),
            ],
            options={
                'verbose_name': 'Maqola fayli',
                'verbose_name_plural': 'Maqola fayllari',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='app.conference', verbose_name='Konferensiya'),
        ),
    ]
