# Generated by Django 5.1.6 on 2025-04-02 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlerequirement',
            options={'verbose_name': 'Article Talablari', 'verbose_name_plural': 'Article Talablari'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangiliklar', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Editorlar', 'verbose_name_plural': 'Editorlar'},
        ),
        migrations.AddField(
            model_name='conference',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Qoralama'), ('submitted', 'Yuborilgan'), ('under_review', "Ko'rib chiqilmoqda"), ('payment', "To'lov qilish"), ('accepted', 'Qabul qilingan'), ('rejected', 'Rad etilgan'), ('published', 'Chop etilgan')], default='draft', max_length=20, verbose_name='Holat'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, verbose_name='Karta raqami')),
                ('price', models.CharField(max_length=20, verbose_name='Narx')),
                ('description', models.TextField(verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.article', verbose_name='Maqola')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
            },
        ),
    ]
