# Generated by Django 5.1.6 on 2025-04-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_articlerequirement_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlerequirement',
            options={'verbose_name': 'Maqola Talablari', 'verbose_name_plural': 'Maqola Talablari'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Foydalanuvchilar', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['-start_date'], 'verbose_name': 'Jurnal soni', 'verbose_name_plural': 'Jurnal soni'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': "Taqriz a'zolari", 'verbose_name_plural': "Taqriz a'zolari"},
        ),
        migrations.AddField(
            model_name='articlerequirement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='article_requirements/'),
        ),
    ]
