# Generated by Django 5.1.6 on 2025-04-02 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_articlerequirement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlerequirement',
            name='file',
        ),
        migrations.CreateModel(
            name='ArticleRequirementFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='article_requirement_files/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('article_requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.articlerequirement')),
            ],
            options={
                'verbose_name': 'Maqola Talablari Fayllari',
                'verbose_name_plural': 'Maqola Talablari Fayllari',
            },
        ),
    ]
