# Generated by Django 5.1.6 on 2025-04-02 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_articlerequirement_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlerequirementfile',
            name='article_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.articlerequirement'),
        ),
    ]
