# Generated by Django 5.1.6 on 2025-04-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_articlerequirementfile_article_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlerequirementfile',
            name='article_requirement',
        ),
    ]
